apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: rob.killilea@svp.ie
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "dev.svp.ie"
      dns01:
        cloudflare:
          email: rob.killilea@svp.ie
          apiTokenSecretRef:
            name: cf-api-token-secret
            key: api-token
