apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
name: secret-replicator
namespace: secret-replicator
spec:
chart:
    spec:
    chart: secret-replicator
    version: 0.6.x
    sourceRef:
        kind: HelmRepository
        name: kiwigrid
        namespace: flux-system
interval: 15m
timeout: 5m
releaseName: secret-replicator
valuesFrom:
- configMapKeyRef:
    name: secret-replicator-helm-chart-value-overrides
    namespace: secret-replicator
    key: values.yaml # This is the default, but best to be explicit for clarity
